apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: osmg29jv8-python-gitops
  description: This is GitOps manifest for osmg29jv8-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=osmg29jv8-python
    backstage.io/kubernetes-id: osmg29jv8-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: osmg29jv8-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:osmg29jv8-python
