apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: osmg29jv8-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:a5f35ee83cbb4a6c0630eca35c57d8e96f6537bb@sha256:786e5ccf8095e9c151da4a2b7a1b9dbba44fb09fb84058ff545d3646ad55a4c1
          name: container-image
