apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: osmg29jv8-python
  janus-idp.io/tekton: osmg29jv8-python
  backstage.io/kubernetes-id: osmg29jv8-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: osmg29jv8-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
